title: Jakub Borowczyk
description: Jakub Borowczyk · Kontratenor · Opera · Teatr

baseurl: ""
url: ""
host: 0.0.0.0

excerpt_separator: "<!-- more -->"

plugins:
  - jekyll-seo-tag
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true

collections:
  - articles
  - repertuar
  - galeria

livereload_ignore:
  - .idea/*

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - tailwind.config.js
  - assets/scss/
  - assets/js/
  - README.md
